### ISSUE TITLE
[1.18.2] Parties Overlay preset resetting on loadup

### ISSUE THREAD

**Issue by VirtualGaming1** [EtherealOnyx/Parties#183]
I just found this mod and looks great and it also bring mod support (that what draw me to this mod) but noticed the main overlay like the hearts thrust and so on above the hotbar is not hiding

I even save setting and restart the game and it still there also I noticed that the preset in the parties overlay reset

![image](https://github.com/EtherealOnyx/Parties/assets/20447403/8c5c2b5c-3df5-4777-863f-d827a63284d7)
![image](https://github.com/EtherealOnyx/Parties/assets/20447403/1d47e56b-1999-43a2-abea-a61d7661180b)

**Comment by EtherealOnyx** [comment]
I originally implemented methods where hiding the UI was possible for mods and vanilla, but as support for more mods grew, the more I questioned whether the idea was ethical or not - It usually involved modifying another mod's code to be able to stop their UI from rendering. Due to this reason, I removed most support for these features while I pondered over the idea.

Considering that the client settings are still there, however, perhaps its best to just re-implement them for the time being - I will look into re-adding this functionality for the next version right away.

As for your second issue, I will investigate the overlays being reset as well. I apologize for the inconvenience.

**Comment by VirtualGaming1** [comment]
ok for some reason the overlay hide next time I restarted Minecraft (minecraft is being minecraft at times) but the presets still resetting to default.

Also I was not inspecting a quick responds. so thank you for quick responds.

**Comment by EtherealOnyx** [comment]
I would need more information regarding the overlay hiding, if you can provide it.

I figured out the issue of the overlay not saving, I believe. As of now, due to an oversight, the overlay only saves if the position of the frame has changed. This would be an easy fix.

**Comment by VirtualGaming1** [comment]
> I would need more information regarding the overlay hiding, if you can provide it.
I am working on a Test world (SP) to test out the mods for the modpack and I think of leaving the world and rejoin would reload the client config but I fully shut down minecraft and look at my mod list and did not change anything and load it up and the config changed worked.

> I figured out the issue of the overlay not saving, I believe. As of now, due to an oversight, the overlay only saves if the position of the frame has changed. This would be an easy fix.
So here is the funny thing,,, I noticed there is an icon from Cold Sweat that was missing and then I went into the preset and noticed that the temp option was turning it self off so I decided to downgrade Cold Sweat from 2.3-b04b to 2.3-b03c and now the Preset is loading up. so that part was caused by Cold Sweat. I am doing more testing around and let you know if I found anything.

**Comment by EtherealOnyx** [comment]
Oh, I think I understand what you mean. Yes, changing the rendering settings only take effect when you reload your minecraft instance or when you apply the command `/party reload`, but as of now **that command will crash your game.** At first, I thought it was due to an interaction with another mod, but after testing it crashes without any mod. So the only way for the changes to affect your game is if you fully restart the game after applying the client configuration changes.

So you're saying cold sweat v2.3-b04b doesn't work with the mod? Perhaps they changed some internal configurations again. I will look into this.

**Comment by EtherealOnyx** [comment]
ColdSweat had an update that changed the location of one of its classes, which would break support. This has been fixed so the latest version will work when I update the mod.

**Comment by VirtualGaming1** [comment]
>So you're saying cold sweat v2.3-b04b doesn't work with the mod? Perhaps they changed some internal configurations again. I will look into this.

yea it not just that version, its the versions after 2.3-b03c 

>ColdSweat had an update that changed the location of one of its classes, which would break support. This has been fixed so the latest version will work when I update the mod.

That would make since as I am noticing that I am insta freezing in near by areas.

**Comment by EtherealOnyx** [comment]
> That would make since as I am noticing that I am insta freezing in near by areas.


Unfortunately I believe that might be unrelated...

When my mod attempts to access ColdSweat it would throw an error and then support would be promptly disabled right after that and no further interactions will occur.

**Comment by VirtualGaming1** [comment]
> > That would make since as I am noticing that I am insta freezing in near by areas.
> 
> Unfortunately I believe that might be unrelated...
> 
> When my mod attempts to access ColdSweat it would throw an error and then support would be promptly disabled right after that and no further interactions will occur.

I am using 2.3-b03c of Cold Sweat and the insta freezing is Cold Sweat side

**Comment by EtherealOnyx** [comment]
This has been fixed in [Parties-v1.1.1](https://www.curseforge.com/minecraft/mc-mods/parties/files/5472151) The following was addressed:

- Cold Sweat now works (and only works) with the latest version [v2.3-b04b](https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/5428416)
- `/party reload` now works in case you want to load UI settings right away.
- The preset is properly saved after modification and not reverting to default on client restart.

This issue will be closed when CurseForge approves the update.

**Comment by EtherealOnyx** [comment]
This version has been approved on CurseForge. Please use version 1.1.1 for the fixes. Thanks for the report!
